// Lecturer AI insights page wrapping the GeminiPanel for per-subject analysis.
import { useState, useEffect } from 'react';
import GeminiPanel from '../components/GeminiPanel';
import api from '../services/api';

const SUGGESTED = [
  'Which students are most at risk of failing?',
  'What is the overall pass rate trend this trimester?',
  'Which assessment type has the lowest average mark?',
  'How does my class compare to the institution average?',
];

export default function LecturerAIInsights() {
  const [filters,   setFilters]   = useState({ subjects: [], trimesters: [] });
  const [subject,   setSubject]   = useState('');
  const [trimester, setTrimester] = useState('');

  useEffect(() => {
    api.get('/api/explorer/filters')
      .then(r => setFilters({ subjects: r.data.subjects || [], trimesters: r.data.trimesters || [] }))
      .catch(() => {});
  }, []);

  return (
    <div style={s.page}>
      {/* Header */}
      <div style={s.pageHeader}>
        <div>
          <h1 style={s.pageTitle}>AI Insights</h1>
          <p style={s.pageSub}>Gemini-powered analysis of your class performance</p>
        </div>
        <span style={s.geminiBadge}>✦ Powered by Gemini</span>
      </div>

      {/* Scope selectors */}
      <div style={s.scopeCard}>
        <p style={s.scopeLabel}>Scope</p>
        <div style={s.scopeRow}>
          <div style={s.filterGroup}>
            <label style={s.filterLabel}>Subject</label>
            <select style={s.select} value={subject} onChange={e => setSubject(e.target.value)}>
              <option value="">All subjects</option>
              {filters.subjects.map(sv => <option key={sv} value={sv}>{sv}</option>)}
            </select>
          </div>
          <div style={s.filterGroup}>
            <label style={s.filterLabel}>Trimester</label>
            <select style={s.select} value={trimester} onChange={e => setTrimester(e.target.value)}>
              <option value="">All periods</option>
              {filters.trimesters.map(t => <option key={t} value={t}>{t}</option>)}
            </select>
          </div>
          {(subject || trimester) && (
            <button style={s.clearBtn} onClick={() => { setSubject(''); setTrimester(''); }}>
              Clear scope
            </button>
          )}
        </div>
        <p style={s.scopeHint}>
          {subject || trimester
            ? `Insights scoped to: ${[subject, trimester].filter(Boolean).join(' · ')}`
            : 'No scope set — insights will cover all subjects and periods you have access to.'}
        </p>
      </div>

      {/* Suggested questions */}
      <div style={s.suggestCard}>
        <p style={s.suggestTitle}>Suggested questions</p>
        <div style={s.chips}>
          {SUGGESTED.map(q => (
            <span key={q} style={s.chip}>{q}</span>
          ))}
        </div>
      </div>

      {/* Gemini panel */}
      <GeminiPanel subject={subject} trimester={trimester} />

      {/* Info footer */}
      <div style={s.footer}>
        <p style={s.footerText}>
          AI responses are generated by Google Gemini and may not always be accurate.
          Cross-check with the raw data in Explorer before acting on recommendations.
        </p>
      </div>
    </div>
  );
}

const s = {
  page:       { padding: '28px 32px', background: '#F0F4F8', minHeight: '100vh', boxSizing: 'border-box' },
  pageHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 },
  pageTitle:  { margin: 0, fontSize: 20, fontWeight: 700, color: '#1A2E40' },
  pageSub:    { margin: '4px 0 0', fontSize: 13, color: '#64748B' },
  geminiBadge: {
    fontSize: 12, fontWeight: 600, color: '#2E6E8E',
    background: '#EFF6FF', border: '0.5px solid #BFDBFE',
    borderRadius: 20, padding: '6px 14px',
  },

  scopeCard: {
    background: '#fff', border: '0.5px solid #DDE4EA', borderRadius: 10,
    padding: '16px 20px', marginBottom: 16,
  },
  scopeLabel: { margin: '0 0 10px', fontSize: 11, fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: 0.5 },
  scopeRow:   { display: 'flex', flexWrap: 'wrap', alignItems: 'flex-end', gap: 12, marginBottom: 10 },
  filterGroup: { display: 'flex', flexDirection: 'column', gap: 4 },
  filterLabel: { fontSize: 11, fontWeight: 600, color: '#475569', textTransform: 'uppercase', letterSpacing: 0.4 },
  select: {
    border: '0.5px solid #C5D2DC', borderRadius: 8, padding: '8px 12px',
    fontSize: 13, color: '#1E293B', background: '#fff', outline: 'none',
    minWidth: 180, cursor: 'pointer',
  },
  clearBtn: {
    padding: '8px 14px', borderRadius: 8, border: '0.5px solid #C5D2DC',
    background: '#fff', color: '#64748B', fontSize: 12, cursor: 'pointer', alignSelf: 'flex-end',
  },
  scopeHint: { margin: 0, fontSize: 12, color: '#94A3B8', fontStyle: 'italic' },

  suggestCard: {
    background: '#F8FAFC', border: '0.5px solid #DDE4EA', borderRadius: 10,
    padding: '14px 20px', marginBottom: 4,
  },
  suggestTitle: { margin: '0 0 10px', fontSize: 12, fontWeight: 600, color: '#475569' },
  chips: { display: 'flex', flexWrap: 'wrap', gap: 8 },
  chip: {
    fontSize: 12, color: '#2E6E8E', background: '#EFF6FF',
    border: '0.5px solid #BFDBFE', borderRadius: 20, padding: '4px 12px',
    cursor: 'default',
  },

  footer: { marginTop: 16, padding: '0 4px' },
  footerText: { margin: 0, fontSize: 11, color: '#94A3B8', lineHeight: 1.6 },
};
